// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { Post, postBody } from "./getHomeData";
import { posts } from "./getHomeData";

type Data = {
  data: {
    comment: Comment;
  };
  message: string;
};
type Comment = {
  name: string;
  content: string;
  email: string;
};

export default async function handler( // Generated by https://quicktype.io
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  if (req.method == "POST") {
    const comment = req.body?.comment;
    res.status(201).json({
      data: {
        comment,
      },
      message: "success",
    });
  }
}
