// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { Post, postBody } from "./getHomeData";
import { posts } from "./getHomeData";

const fs = require("fs");

type Data = {
  content: Post | null;
  message: string;
};

export default async function handler( // Generated by https://quicktype.io
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  await new Promise((resolve) => setTimeout(resolve, 500));
  const post = posts.filter((p) => p.slug === req.query.slug)[0];
  if (post) {
    res.status(200).json({
      content: {
        ...post,
        body: postBody,
        title: "خطوات عملية حول كيفية بيع المنتجات على الانترنت",
      },
      message: "success",
    });
  } else {
    res.status(404).json({
      content: null,
      message: "Not found",
    });
  }
}
