// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { Post } from "./getHomeData";

const fs = require("fs");

export const post = {
  author: "عبدالله عادل",
  title: " ما هو مستقبل التجارة الإلكترونية ",
  excerpt:
    "من المتوقع أن تزيد المبيعات من 1.3 تريليون في عام 2014 إلى 4.5 تريليون في عام 2021",
  category: "التقارير والدراسات",
  subcategory: "أفكار البزنس",
  created_at: "2019-01-30T12:00:00.000Z",
  id: 1,
  tags: ["#تسويق", "#استراتيجيات", "#بيع المنتجات"],
  is_featured: false,
  image: "/images/posts/1.png",
  slug: "non-maiores-reiciendis",
};

type Data = {
  content: Post;
};

export default async function handler( // Generated by https://quicktype.io
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  // await new Promise((resolve) => setTimeout(resolve, 1000));
  res.status(200).json({ content: post });
}
