// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

type Data = {
  data: {
    email: string;
  };
  message: string;
};

export default async function handler( // Generated by https://quicktype.io
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  if (req.method == "POST") {
    console.log(req.body)
    const email = req.body?.email;
    res.status(201).json({
      data: {
        email,
      },
      message: "success",
    });
  }
}
